In [1]:
import pandas as pd
import altair as alt
import numpy as np
alt.renderers.enable('notebook')
#alt.data_transformers.enable('default', max_rows=None)
pd.set_option('display.max_columns', None)

In [2]:
df15 = pd.read_csv('world-happiness-report/2015new.csv')
df16 = pd.read_csv('world-happiness-report/2016new.csv')
df17 = pd.read_csv('world-happiness-report/2017new.csv')

df15['Upper Confidence Interval'] = df15['Happiness Score']+df15['Standard Error']
df15['Lower Confidence Interval'] = df15['Happiness Score']-df15['Standard Error']
df15 = df15.drop(columns="Standard Error")

In [32]:
df15["year"] = 1955
df16["year"] = 1980
df17["year"] = 2005

In [33]:
df = pd.DataFrame()
df = df.append(df15)
df = df.append(df16, sort= False)
df = df.append(df17, sort= False)
df = df.rename(columns={"Country":"country",
                   "Region":"region",
                   "Happiness Rank":"rank",
                   "Happiness Score":"score",
                   "Economy (GDP per Capita)":"gdp",
                   "Family":"fertility",
                   "Health (Life Expectancy)":"life_expect",
                   "Freedom":"freedom",
                   "Trust (Government Corruption)":"trust",
                   "Generosity":"generosity",
                   "Dystopia Residual":"resid",
                   "Upper Confidence Interval":"uci",
                   "Lower Confidence Interval":"lci"})

In [ ]:
import altair as alt

source = df

brush = alt.selection(type='interval', resolve='global')

base = alt.Chart(source).mark_circle(opacity=0.8).encode(
    y='Happiness Score',
    color=alt.condition(brush, 'Region', alt.ColorValue('gray')),
    tooltip = ['Country', 'Year']
).add_selection(
    brush
).properties(
    width=250,
    height=250
)

base.encode(x='Health (Life Expectancy)') | base.encode(x='Freedom')

In [37]:
with open('gapminder3.json', 'w') as f:
    f.write(df.to_json(orient='records', lines=False))

In [5]:
df.region.unique()

array(['Western Europe', 'North America', 'Australia and New Zealand',
       'Middle East and Northern Africa', 'Latin America and Caribbean',
       'Southeastern Asia', 'Central and Eastern Europe', 'Eastern Asia',
       'Sub-Saharan Africa', 'Southern Asia'], dtype=object)

In [35]:
clust = 0
df['cluster'] = ''
for i in df.region.unique():
    df.loc[df['region'] == i, 'cluster'] = clust
    clust+=1

In [30]:
df.head()

,country,region,rank,score,gdp,fertility,life_expect,freedom,trust,generosity,resid,uci,lci,year,cluster
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,7.62111,7.55289,2015,0
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,7.60984,7.51216,2015,0
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,7.56028,7.49372,2015,0
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,7.56080,7.48320,2015,0
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,7.46253,7.39147,2015,1

In [57]:
clust = 0
df['cluster'] = ''
for i in df.region.unique():
    df.loc[df['region'] == i, 'cluster'] = clust
    clust+=1

In [61]:
with open('happiness.json', 'w') as f:
    f.write(df.to_json(orient='records', lines=False))

In [41]:
df.head()

,country,rank,score,year,gdp_per_cap,fertility,life_expect,region,cluster
0,Afghanistan,141,3.794,2017,0.401477,0.581543,0.180747,Southern Asia,0
1,Afghanistan,154,3.360,2016,0.382270,0.110370,0.173440,Southern Asia,0
2,Afghanistan,153,3.575,2015,0.319820,0.302850,0.303350,Southern Asia,0
3,Albania,109,4.644,2017,0.996193,0.803685,0.731160,Central and Eastern Europe,1
4,Albania,109,4.655,2016,0.955300,0.501630,0.730070,Central and Eastern Europe,1

In [58]:
df.region.unique()

array(['Asia', 'Central and Eastern Europe',
       'Middle East and Northern Africa', 'Sub-Saharan Africa',
       'Latin America and Caribbean', 'Australia and New Zealand',
       'Western Europe', 'North America'], dtype=object)

In [55]:
df.loc[df['region']==('Southern Asia'), 'region'] = 'Asia'
df.loc[df['region']==('Southeastern Asia'), 'region'] = 'Asia'
df.loc[df['region']==('Eastern Asia'), 'region'] = 'Asia'

In [91]:
df = pd.read_csv('happiness_data.csv')
df = df.rename(columns={'score':'happy'})
clust = 0
df['cluster'] = ''
for i in df.region.unique():
    df.loc[df['region'] == i, 'cluster'] = clust
    clust+=1
with open('happiness_big.json', 'w') as f:
    f.write(df.to_json(orient='records', lines=False))

In [86]:
dfyear = df.groupby('country')

In [87]:
dfyear.head()

,country,region,year,score,gdp_per_cap,social,life_expect,freedom,generosity,corruption,positivity,negativity,conf_in_gov,democracy,delivery_quality,cluster
0,South Sudan,Sub-Saharan Africa,2016,2.888,7.359,0.532,50.60,0.440,0.022,0.785,0.615,0.549,0.456,-2.107,-1.963,0
1,South Sudan,Sub-Saharan Africa,2015,4.071,7.537,0.585,50.20,0.512,0.114,0.710,0.586,0.450,0.509,-1.985,-1.847,0
2,South Sudan,Sub-Saharan Africa,2014,3.832,7.568,0.545,49.84,0.567,0.025,0.742,0.614,0.428,0.446,-2.132,-1.787,0
3,Venezuela,Latin America and Caribbean,2017,5.071,9.439,0.896,66.30,0.636,-0.206,0.844,0.726,0.363,0.241,-1.196,-1.744,1
4,Venezuela,Latin America and Caribbean,2016,4.041,9.534,0.902,66.10,0.458,-0.204,0.890,0.688,0.392,0.164,-1.081,-1.720,1
5,Zimbabwe,Sub-Saharan Africa,2009,4.056,7.198,0.806,45.42,0.411,-0.056,0.931,0.736,0.218,0.285,-1.353,-1.718,0
6,Zimbabwe,Sub-Saharan Africa,2008,3.174,7.103,0.843,44.14,0.344,-0.068,0.964,0.631,0.250,0.182,-1.381,-1.702,0
7,Zimbabwe,Sub-Saharan Africa,2010,4.682,7.296,0.857,46.70,0.665,-0.066,0.828,0.748,0.122,0.471,-1.290,-1.694,0
8,Afghanistan,Asia,2008,3.724,7.169,0.451,50.80,0.718,0.178,0.882,0.518,0.258,0.612,-1.930,-1.655,2
9,Zimbabwe,Sub-Saharan Africa,2007,3.280,7.314,0.828,42.86,0.456,-0.062,0.946,0.661,0.265,0.226,-1.340,-1.654,0
10,Afghanistan,Asia,2009,4.402,7.334,0.552,51.20,0.679,0.200,0.850,0.584,0.237,0.612,-2.044,-1.635,2
11,Venezuela,Latin America and Caribbean,2015,5.569,9.655,0.911,65.90,0.512,-0.175,0.813,0.867,0.223,0.213,-1.034,-1.632,1
12,Zimbabwe,Sub-Saharan Africa,2011,4.846,7.419,0.865,48.12,0.633,-0.062,0.830,0.781,0.211,0.426,-1.205,-1.622,0
13,Afghanistan,Asia,2010,4.758,7.387,0.539,51.60,0.600,0.134,0.707,0.618,0.275,0.299,-1.992,-1.617,2
14,Afghanistan,Asia,2011,3.832,7.415,0.521,51.92,0.496,0.172,0.731,0.611,0.267,0.307,-1.919,-1.616,2
15,Venezuela,Latin America and Caribbean,2014,6.136,9.726,0.904,65.86,0.570,-0.223,0.827,0.811,0.244,0.203,-0.968,-1.589,1
16,Central African Republic,Sub-Saharan Africa,2016,2.693,6.466,0.290,44.90,0.624,0.053,0.859,0.579,0.494,0.749,-1.438,-1.575,0
18,Congo (Kinshasa),Sub-Saharan Africa,2011,4.517,6.526,0.744,50.34,0.631,-0.008,0.856,0.617,0.208,0.351,-1.849,-1.562,0
19,Congo (Kinshasa),Sub-Saharan Africa,2009,3.984,6.457,0.733,49.34,0.556,-0.005,0.824,0.491,0.283,0.537,-1.706,-1.561,0
21,Congo (Kinshasa),Sub-Saharan Africa,2017,4.311,6.695,0.670,52.90,0.704,0.085,0.809,0.551,0.404,0.478,-1.872,-1.552,0
22,Central African Republic,Sub-Saharan Africa,2017,3.476,6.494,0.320,45.20,0.645,0.094,0.890,0.614,0.599,0.650,-1.523,-1.539,0
23,Congo (Kinshasa),Sub-Saharan Africa,2012,4.639,6.561,0.770,50.78,0.557,-0.017,0.807,0.634,0.230,0.438,-1.783,-1.528,0
26,Venezuela,Latin America and Caribbean,2013,6.553,9.779,0.896,65.82,0.642,-0.235,0.837,0.840,0.238,0.388,-1.015,-1.483,1
27,Chad,Sub-Saharan Africa,2008,4.632,7.460,0.571,44.14,0.527,0.050,0.944,0.569,0.225,0.349,-1.706,-1.473,0
28,Congo (Kinshasa),Sub-Saharan Africa,2015,3.903,6.700,0.767,52.10,0.574,-0.031,0.866,0.589,0.301,0.274,-1.727,-1.458,0
30,Afghanistan,Asia,2017,2.662,7.498,0.491,52.80,0.427,-0.112,0.954,0.496,0.371,0.261,-1.887,-1.438,2
31,Haiti,Latin America and Caribbean,2017,3.824,7.410,0.647,55.50,0.484,0.381,0.647,0.573,0.322,0.435,-0.721,-1.424,1
32,Chad,Sub-Saharan Africa,2007,4.141,7.462,0.479,43.66,0.295,-0.024,0.874,0.614,0.245,0.228,-1.659,-1.420,0
34,Haiti,Latin America and Caribbean,2016,3.352,7.411,0.584,55.30,0.304,0.291,0.839,0.553,0.367,0.146,-0.752,-1.409,1
38,Iraq,Middle East and Northern Africa,2008,4.590,9.411,0.744,58.32,0.386,-0.097,0.910,0.525,0.448,0.476,-1.787,-1.404,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253,Netherlands,Western Europe,2007,7.452,10.748,0.944,70.80,0.896,0.339,0.445,0.818,0.213,0.662,1.151,1.871,5
1254,Switzerland,Western Europe,2012,7.776,10.936,0.947,72.78,0.945,0.133,0.323,0.859,0.176,0.770,1.529,1.879,5
1257,New Zealand,Australia and New Zealand,2007,7.604,10.394,0.967,71.40,0.878,0.275,0.295,0.854,0.238,0.586,1.361,1.888,7
1259,Denmark,Western Europe,2016,7.558,10.736,0.954,71.80,0.948,0.135,0.210,0.836,0.208,0.468,1.205,1.899,5
1263,New Zealand,Australia and New Zealand,2008,7.381,10.370,0.944,71.60,0.893,0.295,0.334,0.854,0.232,0.465,1.321,1.914,7
1264,Norway,Western Europe,2012,7.678,11.051,0.948,72.24,0.947,0.129,0.368,0.823,0.213,0.663,1.528,1.918,5
1265,Sweden,Western Europe,2017,7.287,10.757,0.914,72.50,0.935,0.163,0.239,0.814,0.175,0.559,1.277,1.928,5
1266,Singapore,Asia,2011,6.561,11.227,0.904,75.02,0.822,-0.160,0.099,0.483,0.144,0.825,0.545,1.931,2
1267,Norway,Western Europe,2015,7.603,11.067,0.947,72.90,0.948,0.238,0.299,0.843,0.209,0.587,1.425,1.931,5
1268,Norway,Western Europe,2014,7.444,11.058,0.941,72.68,0.956,0.162,0.405,0.834,0.194,0.700,1.402,1.933,5
1269,Sweden,Western Europe,2008,7.516,10.680,0.923,71.62,0.912,0.118,0.314,0.804,0.134,0.517,1.325,1.938,5
1270,Sweden,Western Europe,2007,7.241,10.693,0.917,71.48,0.910,0.139,0.289,0.796,0.177,0.562,1.391,1.938,5
1271,Sweden,Western Europe,2014,7.239,10.696,0.933,72.22,0.945,0.196,0.250,0.836,0.208,0.563,1.338,1.940,5
1273,New Zealand,Australia and New Zealand,2013,7.280,10.428,0.958,72.36,0.944,0.233,0.312,0.835,0.151,0.544,1.530,1.952,7
1274,Switzerland,Western Europe,2015,7.572,10.955,0.938,73.20,0.928,0.103,0.210,0.809,0.166,0.788,1.449,1.955,5
1275,Singapore,Asia,2009,6.145,11.062,0.866,74.50,0.776,-0.085,0.035,0.500,0.208,0.974,0.473,1.958,2
1276,Singapore,Asia,2010,6.531,11.186,0.864,74.80,0.846,-0.029,0.060,0.602,0.131,0.905,0.480,1.958,2
1277,Denmark,Western Europe,2015,7.514,10.725,0.960,71.50,0.941,0.218,0.191,0.829,0.218,0.580,1.225,1.959,5
1278,New Zealand,Australia and New Zealand,2010,7.224,10.377,0.976,72.00,0.918,0.251,0.321,0.847,0.235,0.639,1.372,1.960,7
1279,Sweden,Western Europe,2016,7.369,10.749,0.912,72.40,0.918,0.139,0.246,0.816,0.201,0.486,1.291,1.960,5
1280,Singapore,Asia,2013,6.533,11.276,0.808,75.46,0.827,0.104,0.242,0.770,0.148,0.856,0.707,1.961,2
1281,Denmark,Western Europe,2014,7.508,10.716,0.956,71.28,0.942,0.113,0.237,0.832,0.233,0.458,1.238,1.962,5
1282,Switzerland,Western Europe,2016,7.459,10.958,0.928,73.50,0.934,0.083,0.302,0.779,0.206,0.799,1.419,1.964,5
1286,Finland,Western Europe,2016,7.660,10.588,0.954,71.70,0.948,-0.031,0.250,0.797,0.182,0.486,1.265,1.975,5
1289,Finland,Western Europe,2008,7.671,10.659,0.951,70.08,0.934,0.023,0.217,0.773,0.144,0.723,1.454,1.980,5
1290,Finland,Western Europe,2015,7.448,10.570,0.948,71.60,0.930,0.107,0.223,0.751,0.191,0.558,1.292,1.997,5
1291,Finland,Western Europe,2017,7.788,10.611,0.964,71.80,0.962,-0.006,0.192,0.787,0.176,0.598,1.311,2.000,5
1294,Singapore,Asia,2007,6.834,11.134,0.921,73.90,0.867,0.283,0.064,0.700,0.114,0.934,0.405,2.009,2
1295,Denmark,Western Europe,2012,7.520,10.700,0.951,70.84,0.933,0.134,0.187,0.774,0.209,0.534,1.295,2.012,5
1305,Finland,Western Europe,2014,7.385,10.572,0.952,71.36,0.933,-0.005,0.265,0.784,0.199,0.469,1.412,2.037,5

In [81]:
with open('happiness.json', 'w') as f:
    f.write(df.to_json(orient='records', lines=False))

In [88]:
df.year.unique()

array([2016, 2015, 2014, 2017, 2009, 2008, 2010, 2007, 2011, 2006, 2012,
       2013, 2005])

In [95]:
dfyear = df.groupby('country')['country']
dfyear.head()

0                    South Sudan
1                    South Sudan
2                    South Sudan
3                      Venezuela
4                      Venezuela
5                       Zimbabwe
6                       Zimbabwe
7                       Zimbabwe
8                    Afghanistan
9                       Zimbabwe
10                   Afghanistan
11                     Venezuela
12                      Zimbabwe
13                   Afghanistan
14                   Afghanistan
15                     Venezuela
16      Central African Republic
18              Congo (Kinshasa)
19              Congo (Kinshasa)
21              Congo (Kinshasa)
22      Central African Republic
23              Congo (Kinshasa)
26                     Venezuela
27                          Chad
28              Congo (Kinshasa)
30                   Afghanistan
31                         Haiti
32                          Chad
34                         Haiti
38                          Iraq
                  ...
1253                 Netherlands
1254                 Switzerland
1257                 New Zealand
1259                     Denmark
1263                 New Zealand
1264                      Norway
1265                      Sweden
1266                   Singapore
1267                      Norway
1268                      Norway
1269                      Sweden
1270                      Sweden
1271                      Sweden
1273                 New Zealand
1274                 Switzerland
1275                   Singapore
1276                   Singapore
1277                     Denmark
1278                 New Zealand
1279                      Sweden
1280                   Singapore
1281                     Denmark
1282                 Switzerland
1286                     Finland
1289                     Finland
1290                     Finland
1291                     Finland
1294                   Singapore
1295                     Denmark
1305                     Finland
Name: country, Length: 695, dtype: object

In [90]:
df.head()

,country,region,year,happy,gdp_per_cap,social,life_expect,freedom,generosity,corruption,positivity,negativity,conf_in_gov,democracy,delivery_quality,cluster
0,South Sudan,Sub-Saharan Africa,2016,2.888,7.359,0.532,50.60,0.440,0.022,0.785,0.615,0.549,0.456,-2.107,-1.963,0
1,South Sudan,Sub-Saharan Africa,2015,4.071,7.537,0.585,50.20,0.512,0.114,0.710,0.586,0.450,0.509,-1.985,-1.847,0
2,South Sudan,Sub-Saharan Africa,2014,3.832,7.568,0.545,49.84,0.567,0.025,0.742,0.614,0.428,0.446,-2.132,-1.787,0
3,Venezuela,Latin America and Caribbean,2017,5.071,9.439,0.896,66.30,0.636,-0.206,0.844,0.726,0.363,0.241,-1.196,-1.744,1
4,Venezuela,Latin America and Caribbean,2016,4.041,9.534,0.902,66.10,0.458,-0.204,0.890,0.688,0.392,0.164,-1.081,-1.720,1

In [131]:
avg_years = np.array([])
for i in df.country.unique():
    years_avail = df.loc[df['country']==i,'year']
    avg_years=np.append(avg_years,len(np.intersect1d(years_avail, range(2005,2018))))

    for j in range(2005,2018):
        if ~np.isin(j,years_avail):
            print('')

Object `np.union` not found.

AttributeError: 'numpy.ndarray' object has no attribute 'mode'